//
// Autogenerated by Thrift Compiler (0.7.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./cloudtrace_types');
//HELPER FUNCTIONS AND STRUCTURES

var TestService_checkTrace_args = function(args) {
  this.tinfo = null;
  this.message = null;
  if (args) {
    if (args.tinfo !== undefined) {
      this.tinfo = args.tinfo;
    }
    if (args.message !== undefined) {
      this.message = args.message;
    }
  }
};
TestService_checkTrace_args.prototype = {};
TestService_checkTrace_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.tinfo = new ttypes.TInfo();
        this.tinfo.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.message = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TestService_checkTrace_args.prototype.write = function(output) {
  output.writeStructBegin('TestService_checkTrace_args');
  if (this.tinfo) {
    output.writeFieldBegin('tinfo', Thrift.Type.STRUCT, 1);
    this.tinfo.write(output);
    output.writeFieldEnd();
  }
  if (this.message) {
    output.writeFieldBegin('message', Thrift.Type.STRING, 2);
    output.writeString(this.message);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TestService_checkTrace_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
TestService_checkTrace_result.prototype = {};
TestService_checkTrace_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TestService_checkTrace_result.prototype.write = function(output) {
  output.writeStructBegin('TestService_checkTrace_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var TestServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
TestServiceClient.prototype = {};
TestServiceClient.prototype.checkTrace = function(tinfo, message, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_checkTrace(tinfo, message);
};

TestServiceClient.prototype.send_checkTrace = function(tinfo, message) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('checkTrace', Thrift.MessageType.CALL, this.seqid);
  var args = new TestService_checkTrace_args();
  args.tinfo = tinfo;
  args.message = message;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TestServiceClient.prototype.recv_checkTrace = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TestService_checkTrace_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('checkTrace failed: unknown result');
};
var TestServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
TestServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

TestServiceProcessor.prototype.process_checkTrace = function(seqid, input, output) {
  var args = new TestService_checkTrace_args();
  args.read(input);
  input.readMessageEnd();
  var result = new TestService_checkTrace_result();
  this._handler.checkTrace(args.tinfo, args.message, function (success) {
    result.success = success;
    output.writeMessageBegin("checkTrace", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

